### ISSUE TITLE
New User interaction

### ISSUE THREAD

**Issue by LightDestory** [UNICT-DMI/Telegram-DMI-Bot#174]
While I was working on #173 I throught that the current user interaction could be improved.

Right now there are multiple ways for the use to access a specific feature, this fact is working against the #122 proposal because if the users access from a inline command it is useless to display a "return back" button because there isn't any "previous" navigation.

I think we could force the use of the "help" menu as unique access point for all the features of the bot, by implementing all the features with a wizard, like exam search feature, or requiring command line input only for essential data like prof's names.

I was testing internally a new call_back method: "featurerequest_handler" that uses the match: "fr_*" which runs command like a normal slash-command does.

It is a proposal becuase it needs an entire review of the current interaction method.

What do you think?

**Comment by Helias** [comment]
I agree with this, it seems easier for the final user.
In the end, even the ipad/iphone have only "one button" to lead them to everything.

**Comment by TendTo** [comment]
Personally, I prefer to leave things are they are now.
With the recent improvements, the help menu is more navigable, but I don't think it needs to be the only way to access the functions, since it would just remove a feature.
Furthermore, the most recent Telegram updates have made even easier to access the bot commands for mobile users with the menu button.
